#!/bin/bash
# This script installs or copies all the right files to the right location.
#

CWD=$(dirname "$(realpath -s $0)")
NC='\033[0m' # No Color
OS=`uname -o`
YELLOW='\033[1;33m'

copy()
{
    if [ ! -f "$2" ]; then
        printf "Copying [${YELLOW}$1${NC}] -> [${YELLOW}$2${NC}]\n"
        cp -f "$1" "$2"
        return
    fi

    if [ "$1" -ot "$2" ]; then
        printf "Skip copying [${YELLOW}$1${NC}] -> [${YELLOW}$2${NC}]\n"
        return
    fi

    printf "Copying [${YELLOW}$1${NC}] -> [${YELLOW}$2${NC}]\n"
    cp -f "$1" "$2"
}

main()
{
    clear
    read -p "Press [Enter] key to install files into HOME directory at . . ."

    if [ -z "$HOME" ]; then
        printf "Install failed: ${YELLOW}\$HOME${NC} environment variable not set.\n"
        exit 1
    fi

    if [ ! -d "$HOME" ]; then
        printf "Install failed: [${YELLOW}$HOME${NC}] folder was not found.\n"
        exit 1
    fi

    cat .bashrc > "${HOME}/.bashrc"
    if [ "${OS}" == "GNU/Linux" ]; then
        printf "Customizing Linux configuration . . . \n"
        cat .bashrc.linux >> "${HOME}/.bashrc"
    else
        printf "Customizing MSys configuration . . . \n"
        cat .bashrc.win >> "${HOME}/.bashrc"
    fi
    copy "${CWD}/.bash_profile" "${HOME}/.bash_profile"
}

main
